version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_DB: posgtres
      POSTGRES_USER: vaces8v
      POSTGRES_PASSWORD: 66768932
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - p_data:/var/lib/postgresql/data
    networks:
      - app-network
    profiles:
      - database

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "4200:4200"
    restart: always
    networks:
      - app-network
    profiles:
      - nest-profile

networks:
  app-network:
    driver: bridge

volumes:
  p_data: